fraseDigitadaPeloUsuario = input('Digite algume coisa: ').strip()
print('Analizando a frase "{}"'.format(fraseDigitadaPeloUsuario))
print('A letra A aparece {} vezes na frase.'.format(fraseDigitadaPeloUsuario.upper().count('A')))
print('A primeira letra A apareceu na posição {}.'.format(fraseDigitadaPeloUsuario.upper().find('A') + 1))
print('A última letra A apareceu na posição {}.'.format(fraseDigitadaPeloUsuario.upper().rfind('A') + 1))
